#!/bin/bash

SCRIPTDIR="$(cd "$(dirname "$0")" && pwd)"

while test -n "$1"
do
  test -d "$SCRIPTDIR/$1" && (ls -1 "$SCRIPTDIR/$1" | while read f; do test -x "$SCRIPTDIR/$1/$f" && "$SCRIPTDIR/$1/$f"; done)
  shift
done
