#!/bin/bash

# Set your test parameters here for awk
AWKPARAMS=()
# Use this variable to enforce a specific awk version
AWKPROGRAM=/usr/bin/gawk

# Find our script location, and set awkpath
SCRIPTDIR="$(cd "$(dirname "$0")" && pwd)"
export AWKPATH="$SCRIPTDIR/../../include"

# Execute the test - will output data to an awk process from this file that is executed from this file ...
# See below

. "$SCRIPTDIR/../include/performtest.sh"

---  data  ---
  "\\hello \\\" world\\"
" \" \\\\"
" \" \\\\"
"\\" "It works"
--- expect ---
\hello \" world\
 " \\
" \\
\
It works
--- script ---

@include "json.awk"

BEGIN {
	json_initparser(parser)
	parser["trimall"] = 0
	json_parsefrominput(parser)
	print parser["data"]
	json_parsefrominput(parser)
	print parser["data"]
	parser["trimall"] = 1
	json_parsefrominput(parser)
	print parser["data"]
	json_parsefrominput(parser)
	print parser["data"]
	json_parsefrominput(parser)
	print parser["data"]
}
