#!/bin/bash

# Set your test parameters here for awk
AWKPARAMS=("-v" "var=test")
# Use this variable to enforce a specific awk version
AWKPROGRAM=/usr/bin/gawk

# Find our script location, and set awkpath
SCRIPTDIR="$(cd "$(dirname "$0")" && pwd)"
export AWKPATH="$SCRIPTDIR/../../include"

# Execute the test - will output data to an awk process from this file that is executed from this file ...
# See below

. "$SCRIPTDIR/../include/performtest.sh"

---  data  ---

This is data

--- expect ---
Hello world test
got 
got This is data
got 
--- script ---

@include "json.awk"

BEGIN { print "Hello world " var }

{print "got",$0}
